services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_etl:/var/lib/postgresql/data

volumes:
  pgdata_etl:
